version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: app_database
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: vinicius14/person_management
    restart: always
    build: ./person_management
    working_dir: /app
    container_name: person_management
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/app_database
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
      SPRING_APPLICATION_NAME: person_management
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
